name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black

      - name: Format Python code with Black
        run: black .

      - name: Commit formatted code
        run: |
          git config --global user.email "vaibhavsahai2003@example.com"
          git config --global user.name "Vaibhav-Sahai"
          git add .
          git commit -m "Format code with black" || echo "No changes to commit"
          git push || echo "No changes to push"

      - name: Super-Linter
        uses: super-linter/super-linter@v5.7.2
        env:
          VALIDATE_ALL_CODEBASE: false
          VALIDATE_PYTHON: true
          DEFAULT_BRANCH: main
